//go:build !harfbuzz

// Code generated by "stringer -type Script"; DO NOT EDIT.

package text

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScriptInvalid-0]
	_ = x[ScriptCommon-1517910393]
	_ = x[ScriptInherited-1516858984]
	_ = x[ScriptUnknown-1517976186]
	_ = x[Arabic-1098015074]
	_ = x[Armenian-1098018158]
	_ = x[Bengali-1113943655]
	_ = x[Cyrillic-1132032620]
	_ = x[Devanagari-1147500129]
	_ = x[Georgian-1197830002]
	_ = x[Greek-1198679403]
	_ = x[Gujarati-1198877298]
	_ = x[Gurmukhi-1198879349]
	_ = x[Hangul-1214344807]
	_ = x[Han-1214344809]
	_ = x[Hebrew-1214603890]
	_ = x[Hiragana-1214870113]
	_ = x[Kannada-1265525857]
	_ = x[Katakana-1264676449]
	_ = x[Lao-1281453935]
	_ = x[Latin-1281455214]
	_ = x[Malayalam-1298954605]
	_ = x[Oriya-1332902241]
	_ = x[Tamil-1415671148]
	_ = x[Telugu-1415933045]
	_ = x[Thai-1416126825]
	_ = x[Tibetan-1416192628]
	_ = x[Bopomofo-1114599535]
	_ = x[Braille-1114792297]
	_ = x[CanadianSyllabics-1130458739]
	_ = x[Cherokee-1130915186]
	_ = x[Ethiopic-1165256809]
	_ = x[Khmer-1265134962]
	_ = x[Mongolian-1299148391]
	_ = x[Myanmar-1299803506]
	_ = x[Ogham-1332175213]
	_ = x[Runic-1383427698]
	_ = x[Sinhala-1399418472]
	_ = x[Syriac-1400468067]
	_ = x[Thaana-1416126817]
	_ = x[Yi-1500080489]
	_ = x[Deseret-1148416628]
	_ = x[Gothic-1198486632]
	_ = x[OldItalic-1232363884]
	_ = x[Buhid-1114990692]
	_ = x[Hanunoo-1214344815]
	_ = x[Tagalog-1416064103]
	_ = x[Tagbanwa-1415669602]
	_ = x[Cypriot-1131442804]
	_ = x[Limbu-1281977698]
	_ = x[LinearB-1281977954]
	_ = x[Osmanya-1332964705]
	_ = x[Shavian-1399349623]
	_ = x[TaiLe-1415670885]
	_ = x[Ugaritic-1432838514]
	_ = x[Buginese-1114990441]
	_ = x[Coptic-1131376756]
	_ = x[Glagolitic-1198285159]
	_ = x[Kharoshthi-1265131890]
	_ = x[NewTaiLue-1415670901]
	_ = x[OldPersian-1483761007]
	_ = x[SylotiNagri-1400466543]
	_ = x[Tifinagh-1415999079]
	_ = x[Balinese-1113681001]
	_ = x[Cuneiform-1483961720]
	_ = x[Nko-1315663727]
	_ = x[PhagsPa-1349017959]
	_ = x[Phoenician-1349021304]
	_ = x[Carian-1130459753]
	_ = x[Cham-1130914157]
	_ = x[KayahLi-1264675945]
	_ = x[Lepcha-1281716323]
	_ = x[Lycian-1283023721]
	_ = x[Lydian-1283023977]
	_ = x[OlChiki-1332503403]
	_ = x[Rejang-1382706791]
	_ = x[Saurashtra-1398895986]
	_ = x[Sundanese-1400204900]
	_ = x[Vai-1449224553]
	_ = x[Avestan-1098281844]
	_ = x[Bamum-1113681269]
	_ = x[EgyptianHieroglyphs-1164409200]
	_ = x[ImperialAramaic-1098018153]
	_ = x[InscriptionalPahlavi-1349020777]
	_ = x[InscriptionalParthian-1349678185]
	_ = x[Javanese-1247901281]
	_ = x[Kaithi-1265920105]
	_ = x[Lisu-1281979253]
	_ = x[MeeteiMayek-1299473769]
	_ = x[OldSouthArabian-1398895202]
	_ = x[OldTurkic-1332898664]
	_ = x[Samaritan-1398893938]
	_ = x[TaiTham-1281453665]
	_ = x[TaiViet-1415673460]
	_ = x[Batak-1113683051]
	_ = x[Brahmi-1114792296]
	_ = x[Mandaic-1298230884]
	_ = x[Chakma-1130457965]
	_ = x[MeroiticCursive-1298494051]
	_ = x[MeroiticHieroglyphs-1298494063]
	_ = x[Miao-1349284452]
	_ = x[Sharada-1399353956]
	_ = x[SoraSompeng-1399812705]
	_ = x[Takri-1415670642]
	_ = x[BassaVah-1113682803]
	_ = x[CaucasianAlbanian-1097295970]
	_ = x[Duployan-1148547180]
	_ = x[Elbasan-1164730977]
	_ = x[Grantha-1198678382]
	_ = x[Khojki-1265135466]
	_ = x[Khudawadi-1399418468]
	_ = x[LinearA-1281977953]
	_ = x[Mahajani-1298229354]
	_ = x[Manichaean-1298230889]
	_ = x[MendeKikakui-1298493028]
	_ = x[Modi-1299145833]
	_ = x[Mro-1299345263]
	_ = x[Nabataean-1315070324]
	_ = x[OldNorthArabian-1315009122]
	_ = x[OldPermic-1348825709]
	_ = x[PahawhHmong-1215131239]
	_ = x[Palmyrene-1348562029]
	_ = x[PauCinHau-1348564323]
	_ = x[PsalterPahlavi-1349020784]
	_ = x[Siddham-1399415908]
	_ = x[Tirhuta-1416196712]
	_ = x[WarangCiti-1466004065]
	_ = x[Adlam-1097100397]
	_ = x[Bhaiksuki-1114139507]
	_ = x[Marchen-1298231907]
	_ = x[Osage-1332963173]
	_ = x[Tangut-1415671399]
	_ = x[Newa-1315272545]
	_ = x[MasaramGondi-1198485101]
	_ = x[Nushu-1316186229]
	_ = x[Soyombo-1399814511]
	_ = x[ZanabazarSquare-1516334690]
	_ = x[Dogra-1148151666]
	_ = x[GunjalaGondi-1198485095]
	_ = x[HanifiRohingya-1383032935]
	_ = x[Makasar-1298230113]
	_ = x[Medefaidrin-1298490470]
	_ = x[OldSogdian-1399809903]
	_ = x[Sogdian-1399809892]
	_ = x[Elymaic-1164736877]
	_ = x[Nandinagari-1315008100]
	_ = x[NyiakengPuachueHmong-1215131248]
	_ = x[Wancho-1466132591]
	_ = x[Chorasmian-1130918515]
	_ = x[DivesAkuru-1147756907]
	_ = x[KhitanSmallScript-1265202291]
	_ = x[Yezidi-1499822697]
}

const _Script_name = "ScriptInvalidAdlamCaucasianAlbanianArabicImperialAramaicArmenianAvestanBalineseBamumBassaVahBatakBengaliBhaiksukiBopomofoBrahmiBrailleBugineseBuhidChakmaCanadianSyllabicsCarianChamCherokeeChorasmianCopticCypriotCyrillicDevanagariDivesAkuruDograDeseretDuployanEgyptianHieroglyphsElbasanElymaicEthiopicGeorgianGlagoliticGunjalaGondiMasaramGondiGothicGranthaGreekGujaratiGurmukhiHangulHanHanunooHebrewHiraganaPahawhHmongNyiakengPuachueHmongOldItalicJavaneseKayahLiKatakanaKharoshthiKhmerKhojkiKhitanSmallScriptKannadaKaithiTaiThamLaoLatinLepchaLimbuLinearALinearBLisuLycianLydianMahajaniMakasarMandaicManichaeanMarchenMedefaidrinMendeKikakuiMeroiticCursiveMeroiticHieroglyphsMalayalamModiMongolianMroMeeteiMayekMyanmarNandinagariOldNorthArabianNabataeanNewaNkoNushuOghamOlChikiOldTurkicOriyaOsageOsmanyaPalmyrenePauCinHauOldPermicPhagsPaInscriptionalPahlaviPsalterPahlaviPhoenicianMiaoInscriptionalParthianRejangHanifiRohingyaRunicSamaritanOldSouthArabianSaurashtraShavianSharadaSiddhamKhudawadiSinhalaSogdianOldSogdianSoraSompengSoyomboSundaneseSylotiNagriSyriacTagbanwaTakriTaiLeNewTaiLueTamilTangutTaiVietTeluguTifinaghTagalogThaanaThaiTibetanTirhutaUgariticVaiWarangCitiWanchoOldPersianCuneiformYezidiYiZanabazarSquareScriptInheritedScriptCommonScriptUnknown"

var _Script_map = map[Script]string{
	0:          _Script_name[0:13],
	1097100397: _Script_name[13:18],
	1097295970: _Script_name[18:35],
	1098015074: _Script_name[35:41],
	1098018153: _Script_name[41:56],
	1098018158: _Script_name[56:64],
	1098281844: _Script_name[64:71],
	1113681001: _Script_name[71:79],
	1113681269: _Script_name[79:84],
	1113682803: _Script_name[84:92],
	1113683051: _Script_name[92:97],
	1113943655: _Script_name[97:104],
	1114139507: _Script_name[104:113],
	1114599535: _Script_name[113:121],
	1114792296: _Script_name[121:127],
	1114792297: _Script_name[127:134],
	1114990441: _Script_name[134:142],
	1114990692: _Script_name[142:147],
	1130457965: _Script_name[147:153],
	1130458739: _Script_name[153:170],
	1130459753: _Script_name[170:176],
	1130914157: _Script_name[176:180],
	1130915186: _Script_name[180:188],
	1130918515: _Script_name[188:198],
	1131376756: _Script_name[198:204],
	1131442804: _Script_name[204:211],
	1132032620: _Script_name[211:219],
	1147500129: _Script_name[219:229],
	1147756907: _Script_name[229:239],
	1148151666: _Script_name[239:244],
	1148416628: _Script_name[244:251],
	1148547180: _Script_name[251:259],
	1164409200: _Script_name[259:278],
	1164730977: _Script_name[278:285],
	1164736877: _Script_name[285:292],
	1165256809: _Script_name[292:300],
	1197830002: _Script_name[300:308],
	1198285159: _Script_name[308:318],
	1198485095: _Script_name[318:330],
	1198485101: _Script_name[330:342],
	1198486632: _Script_name[342:348],
	1198678382: _Script_name[348:355],
	1198679403: _Script_name[355:360],
	1198877298: _Script_name[360:368],
	1198879349: _Script_name[368:376],
	1214344807: _Script_name[376:382],
	1214344809: _Script_name[382:385],
	1214344815: _Script_name[385:392],
	1214603890: _Script_name[392:398],
	1214870113: _Script_name[398:406],
	1215131239: _Script_name[406:417],
	1215131248: _Script_name[417:437],
	1232363884: _Script_name[437:446],
	1247901281: _Script_name[446:454],
	1264675945: _Script_name[454:461],
	1264676449: _Script_name[461:469],
	1265131890: _Script_name[469:479],
	1265134962: _Script_name[479:484],
	1265135466: _Script_name[484:490],
	1265202291: _Script_name[490:507],
	1265525857: _Script_name[507:514],
	1265920105: _Script_name[514:520],
	1281453665: _Script_name[520:527],
	1281453935: _Script_name[527:530],
	1281455214: _Script_name[530:535],
	1281716323: _Script_name[535:541],
	1281977698: _Script_name[541:546],
	1281977953: _Script_name[546:553],
	1281977954: _Script_name[553:560],
	1281979253: _Script_name[560:564],
	1283023721: _Script_name[564:570],
	1283023977: _Script_name[570:576],
	1298229354: _Script_name[576:584],
	1298230113: _Script_name[584:591],
	1298230884: _Script_name[591:598],
	1298230889: _Script_name[598:608],
	1298231907: _Script_name[608:615],
	1298490470: _Script_name[615:626],
	1298493028: _Script_name[626:638],
	1298494051: _Script_name[638:653],
	1298494063: _Script_name[653:672],
	1298954605: _Script_name[672:681],
	1299145833: _Script_name[681:685],
	1299148391: _Script_name[685:694],
	1299345263: _Script_name[694:697],
	1299473769: _Script_name[697:708],
	1299803506: _Script_name[708:715],
	1315008100: _Script_name[715:726],
	1315009122: _Script_name[726:741],
	1315070324: _Script_name[741:750],
	1315272545: _Script_name[750:754],
	1315663727: _Script_name[754:757],
	1316186229: _Script_name[757:762],
	1332175213: _Script_name[762:767],
	1332503403: _Script_name[767:774],
	1332898664: _Script_name[774:783],
	1332902241: _Script_name[783:788],
	1332963173: _Script_name[788:793],
	1332964705: _Script_name[793:800],
	1348562029: _Script_name[800:809],
	1348564323: _Script_name[809:818],
	1348825709: _Script_name[818:827],
	1349017959: _Script_name[827:834],
	1349020777: _Script_name[834:854],
	1349020784: _Script_name[854:868],
	1349021304: _Script_name[868:878],
	1349284452: _Script_name[878:882],
	1349678185: _Script_name[882:903],
	1382706791: _Script_name[903:909],
	1383032935: _Script_name[909:923],
	1383427698: _Script_name[923:928],
	1398893938: _Script_name[928:937],
	1398895202: _Script_name[937:952],
	1398895986: _Script_name[952:962],
	1399349623: _Script_name[962:969],
	1399353956: _Script_name[969:976],
	1399415908: _Script_name[976:983],
	1399418468: _Script_name[983:992],
	1399418472: _Script_name[992:999],
	1399809892: _Script_name[999:1006],
	1399809903: _Script_name[1006:1016],
	1399812705: _Script_name[1016:1027],
	1399814511: _Script_name[1027:1034],
	1400204900: _Script_name[1034:1043],
	1400466543: _Script_name[1043:1054],
	1400468067: _Script_name[1054:1060],
	1415669602: _Script_name[1060:1068],
	1415670642: _Script_name[1068:1073],
	1415670885: _Script_name[1073:1078],
	1415670901: _Script_name[1078:1087],
	1415671148: _Script_name[1087:1092],
	1415671399: _Script_name[1092:1098],
	1415673460: _Script_name[1098:1105],
	1415933045: _Script_name[1105:1111],
	1415999079: _Script_name[1111:1119],
	1416064103: _Script_name[1119:1126],
	1416126817: _Script_name[1126:1132],
	1416126825: _Script_name[1132:1136],
	1416192628: _Script_name[1136:1143],
	1416196712: _Script_name[1143:1150],
	1432838514: _Script_name[1150:1158],
	1449224553: _Script_name[1158:1161],
	1466004065: _Script_name[1161:1171],
	1466132591: _Script_name[1171:1177],
	1483761007: _Script_name[1177:1187],
	1483961720: _Script_name[1187:1196],
	1499822697: _Script_name[1196:1202],
	1500080489: _Script_name[1202:1204],
	1516334690: _Script_name[1204:1219],
	1516858984: _Script_name[1219:1234],
	1517910393: _Script_name[1234:1246],
	1517976186: _Script_name[1246:1259],
}

func (i Script) String() string {
	if str, ok := _Script_map[i]; ok {
		return str
	}
	return "Script(" + strconv.FormatInt(int64(i), 10) + ")"
}
