// +build !harfbuzz

// Code generated by "stringer -type Script"; DO NOT EDIT.

package text

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScriptInvalid-0]
	_ = x[ScriptCommon-2054781305]
	_ = x[ScriptInherited-2053729896]
	_ = x[ScriptUnknown-2054847098]
	_ = x[Arabic-1634885986]
	_ = x[Armenian-1634889070]
	_ = x[Bengali-1650814567]
	_ = x[Cyrillic-1668903532]
	_ = x[Devanagari-1684371041]
	_ = x[Georgian-1734700914]
	_ = x[Greek-1735550315]
	_ = x[Gujarati-1735748210]
	_ = x[Gurmukhi-1735750261]
	_ = x[Hangul-1751215719]
	_ = x[Han-1751215721]
	_ = x[Hebrew-1751474802]
	_ = x[Hiragana-1751741025]
	_ = x[Kannada-1802396769]
	_ = x[Katakana-1801547361]
	_ = x[Lao-1818324847]
	_ = x[Latin-1818326126]
	_ = x[Malayalam-1835825517]
	_ = x[Oriya-1869773153]
	_ = x[Tamil-1952542060]
	_ = x[Telugu-1952803957]
	_ = x[Thai-1952997737]
	_ = x[Tibetan-1953063540]
	_ = x[Bopomofo-1651470447]
	_ = x[Braille-1651663209]
	_ = x[CanadianSyllabics-1667329651]
	_ = x[Cherokee-1667786098]
	_ = x[Ethiopic-1702127721]
	_ = x[Khmer-1802005874]
	_ = x[Mongolian-1836019303]
	_ = x[Myanmar-1836674418]
	_ = x[Ogham-1869046125]
	_ = x[Runic-1920298610]
	_ = x[Sinhala-1936289384]
	_ = x[Syriac-1937338979]
	_ = x[Thaana-1952997729]
	_ = x[Yi-2036951401]
	_ = x[Deseret-1685287540]
	_ = x[Gothic-1735357544]
	_ = x[OldItalic-1769234796]
	_ = x[Buhid-1651861604]
	_ = x[Hanunoo-1751215727]
	_ = x[Tagalog-1952935015]
	_ = x[Tagbanwa-1952540514]
	_ = x[Cypriot-1668313716]
	_ = x[Limbu-1818848610]
	_ = x[LinearB-1818848866]
	_ = x[Osmanya-1869835617]
	_ = x[Shavian-1936220535]
	_ = x[TaiLe-1952541797]
	_ = x[Ugaritic-1969709426]
	_ = x[Buginese-1651861353]
	_ = x[Coptic-1668247668]
	_ = x[Glagolitic-1735156071]
	_ = x[Kharoshthi-1802002802]
	_ = x[NewTaiLue-1952541813]
	_ = x[OldPersian-2020631919]
	_ = x[SylotiNagri-1937337455]
	_ = x[Tifinagh-1952869991]
	_ = x[Balinese-1650551913]
	_ = x[Cuneiform-2020832632]
	_ = x[Nko-1852534639]
	_ = x[PhagsPa-1885888871]
	_ = x[Phoenician-1885892216]
	_ = x[Carian-1667330665]
	_ = x[Cham-1667785069]
	_ = x[KayahLi-1801546857]
	_ = x[Lepcha-1818587235]
	_ = x[Lycian-1819894633]
	_ = x[Lydian-1819894889]
	_ = x[OlChiki-1869374315]
	_ = x[Rejang-1919577703]
	_ = x[Saurashtra-1935766898]
	_ = x[Sundanese-1937075812]
	_ = x[Vai-1986095465]
	_ = x[Avestan-1635152756]
	_ = x[Bamum-1650552181]
	_ = x[EgyptianHieroglyphs-1701280112]
	_ = x[ImperialAramaic-1634889065]
	_ = x[InscriptionalPahlavi-1885891689]
	_ = x[InscriptionalParthian-1886549097]
	_ = x[Javanese-1784772193]
	_ = x[Kaithi-1802791017]
	_ = x[Lisu-1818850165]
	_ = x[MeeteiMayek-1836344681]
	_ = x[OldSouthArabian-1935766114]
	_ = x[OldTurkic-1869769576]
	_ = x[Samaritan-1935764850]
	_ = x[TaiTham-1818324577]
	_ = x[TaiViet-1952544372]
	_ = x[Batak-1650553963]
	_ = x[Brahmi-1651663208]
	_ = x[Mandaic-1835101796]
	_ = x[Chakma-1667328877]
	_ = x[MeroiticCursive-1835364963]
	_ = x[MeroiticHieroglyphs-1835364975]
	_ = x[Miao-1886155364]
	_ = x[Sharada-1936224868]
	_ = x[SoraSompeng-1936683617]
	_ = x[Takri-1952541554]
	_ = x[BassaVah-1650553715]
	_ = x[CaucasianAlbanian-1634166882]
	_ = x[Duployan-1685418092]
	_ = x[Elbasan-1701601889]
	_ = x[Grantha-1735549294]
	_ = x[Khojki-1802006378]
	_ = x[Khudawadi-1936289380]
	_ = x[LinearA-1818848865]
	_ = x[Mahajani-1835100266]
	_ = x[Manichaean-1835101801]
	_ = x[MendeKikakui-1835363940]
	_ = x[Modi-1836016745]
	_ = x[Mro-1836216175]
	_ = x[Nabataean-1851941236]
	_ = x[OldNorthArabian-1851880034]
	_ = x[OldPermic-1885696621]
	_ = x[PahawhHmong-1752002151]
	_ = x[Palmyrene-1885432941]
	_ = x[PauCinHau-1885435235]
	_ = x[PsalterPahlavi-1885891696]
	_ = x[Siddham-1936286820]
	_ = x[Tirhuta-1953067624]
	_ = x[WarangCiti-2002874977]
	_ = x[Adlam-1633971309]
	_ = x[Bhaiksuki-1651010419]
	_ = x[Marchen-1835102819]
	_ = x[Osage-1869834085]
	_ = x[Tangut-1952542311]
	_ = x[Newa-1852143457]
	_ = x[MasaramGondi-1735356013]
	_ = x[Nushu-1853057141]
	_ = x[Soyombo-1936685423]
	_ = x[ZanabazarSquare-2053205602]
	_ = x[Dogra-1685022578]
	_ = x[GunjalaGondi-1735356007]
	_ = x[HanifiRohingya-1919903847]
	_ = x[Makasar-1835101025]
	_ = x[Medefaidrin-1835361382]
	_ = x[OldSogdian-1936680815]
	_ = x[Sogdian-1936680804]
	_ = x[Elymaic-1701607789]
	_ = x[Nandinagari-1851879012]
	_ = x[NyiakengPuachueHmong-1752002160]
	_ = x[Wancho-2003003503]
	_ = x[Chorasmian-1667789427]
	_ = x[DivesAkuru-1684627819]
	_ = x[KhitanSmallScript-1802073203]
	_ = x[Yezidi-2036693609]
}

const _Script_name = "ScriptInvalidAdlamCaucasianAlbanianArabicImperialAramaicArmenianAvestanBalineseBamumBassaVahBatakBengaliBhaiksukiBopomofoBrahmiBrailleBugineseBuhidChakmaCanadianSyllabicsCarianChamCherokeeChorasmianCopticCypriotCyrillicDevanagariDivesAkuruDograDeseretDuployanEgyptianHieroglyphsElbasanElymaicEthiopicGeorgianGlagoliticGunjalaGondiMasaramGondiGothicGranthaGreekGujaratiGurmukhiHangulHanHanunooHebrewHiraganaPahawhHmongNyiakengPuachueHmongOldItalicJavaneseKayahLiKatakanaKharoshthiKhmerKhojkiKhitanSmallScriptKannadaKaithiTaiThamLaoLatinLepchaLimbuLinearALinearBLisuLycianLydianMahajaniMakasarMandaicManichaeanMarchenMedefaidrinMendeKikakuiMeroiticCursiveMeroiticHieroglyphsMalayalamModiMongolianMroMeeteiMayekMyanmarNandinagariOldNorthArabianNabataeanNewaNkoNushuOghamOlChikiOldTurkicOriyaOsageOsmanyaPalmyrenePauCinHauOldPermicPhagsPaInscriptionalPahlaviPsalterPahlaviPhoenicianMiaoInscriptionalParthianRejangHanifiRohingyaRunicSamaritanOldSouthArabianSaurashtraShavianSharadaSiddhamKhudawadiSinhalaSogdianOldSogdianSoraSompengSoyomboSundaneseSylotiNagriSyriacTagbanwaTakriTaiLeNewTaiLueTamilTangutTaiVietTeluguTifinaghTagalogThaanaThaiTibetanTirhutaUgariticVaiWarangCitiWanchoOldPersianCuneiformYezidiYiZanabazarSquareScriptInheritedScriptCommonScriptUnknown"

var _Script_map = map[Script]string{
	0:          _Script_name[0:13],
	1633971309: _Script_name[13:18],
	1634166882: _Script_name[18:35],
	1634885986: _Script_name[35:41],
	1634889065: _Script_name[41:56],
	1634889070: _Script_name[56:64],
	1635152756: _Script_name[64:71],
	1650551913: _Script_name[71:79],
	1650552181: _Script_name[79:84],
	1650553715: _Script_name[84:92],
	1650553963: _Script_name[92:97],
	1650814567: _Script_name[97:104],
	1651010419: _Script_name[104:113],
	1651470447: _Script_name[113:121],
	1651663208: _Script_name[121:127],
	1651663209: _Script_name[127:134],
	1651861353: _Script_name[134:142],
	1651861604: _Script_name[142:147],
	1667328877: _Script_name[147:153],
	1667329651: _Script_name[153:170],
	1667330665: _Script_name[170:176],
	1667785069: _Script_name[176:180],
	1667786098: _Script_name[180:188],
	1667789427: _Script_name[188:198],
	1668247668: _Script_name[198:204],
	1668313716: _Script_name[204:211],
	1668903532: _Script_name[211:219],
	1684371041: _Script_name[219:229],
	1684627819: _Script_name[229:239],
	1685022578: _Script_name[239:244],
	1685287540: _Script_name[244:251],
	1685418092: _Script_name[251:259],
	1701280112: _Script_name[259:278],
	1701601889: _Script_name[278:285],
	1701607789: _Script_name[285:292],
	1702127721: _Script_name[292:300],
	1734700914: _Script_name[300:308],
	1735156071: _Script_name[308:318],
	1735356007: _Script_name[318:330],
	1735356013: _Script_name[330:342],
	1735357544: _Script_name[342:348],
	1735549294: _Script_name[348:355],
	1735550315: _Script_name[355:360],
	1735748210: _Script_name[360:368],
	1735750261: _Script_name[368:376],
	1751215719: _Script_name[376:382],
	1751215721: _Script_name[382:385],
	1751215727: _Script_name[385:392],
	1751474802: _Script_name[392:398],
	1751741025: _Script_name[398:406],
	1752002151: _Script_name[406:417],
	1752002160: _Script_name[417:437],
	1769234796: _Script_name[437:446],
	1784772193: _Script_name[446:454],
	1801546857: _Script_name[454:461],
	1801547361: _Script_name[461:469],
	1802002802: _Script_name[469:479],
	1802005874: _Script_name[479:484],
	1802006378: _Script_name[484:490],
	1802073203: _Script_name[490:507],
	1802396769: _Script_name[507:514],
	1802791017: _Script_name[514:520],
	1818324577: _Script_name[520:527],
	1818324847: _Script_name[527:530],
	1818326126: _Script_name[530:535],
	1818587235: _Script_name[535:541],
	1818848610: _Script_name[541:546],
	1818848865: _Script_name[546:553],
	1818848866: _Script_name[553:560],
	1818850165: _Script_name[560:564],
	1819894633: _Script_name[564:570],
	1819894889: _Script_name[570:576],
	1835100266: _Script_name[576:584],
	1835101025: _Script_name[584:591],
	1835101796: _Script_name[591:598],
	1835101801: _Script_name[598:608],
	1835102819: _Script_name[608:615],
	1835361382: _Script_name[615:626],
	1835363940: _Script_name[626:638],
	1835364963: _Script_name[638:653],
	1835364975: _Script_name[653:672],
	1835825517: _Script_name[672:681],
	1836016745: _Script_name[681:685],
	1836019303: _Script_name[685:694],
	1836216175: _Script_name[694:697],
	1836344681: _Script_name[697:708],
	1836674418: _Script_name[708:715],
	1851879012: _Script_name[715:726],
	1851880034: _Script_name[726:741],
	1851941236: _Script_name[741:750],
	1852143457: _Script_name[750:754],
	1852534639: _Script_name[754:757],
	1853057141: _Script_name[757:762],
	1869046125: _Script_name[762:767],
	1869374315: _Script_name[767:774],
	1869769576: _Script_name[774:783],
	1869773153: _Script_name[783:788],
	1869834085: _Script_name[788:793],
	1869835617: _Script_name[793:800],
	1885432941: _Script_name[800:809],
	1885435235: _Script_name[809:818],
	1885696621: _Script_name[818:827],
	1885888871: _Script_name[827:834],
	1885891689: _Script_name[834:854],
	1885891696: _Script_name[854:868],
	1885892216: _Script_name[868:878],
	1886155364: _Script_name[878:882],
	1886549097: _Script_name[882:903],
	1919577703: _Script_name[903:909],
	1919903847: _Script_name[909:923],
	1920298610: _Script_name[923:928],
	1935764850: _Script_name[928:937],
	1935766114: _Script_name[937:952],
	1935766898: _Script_name[952:962],
	1936220535: _Script_name[962:969],
	1936224868: _Script_name[969:976],
	1936286820: _Script_name[976:983],
	1936289380: _Script_name[983:992],
	1936289384: _Script_name[992:999],
	1936680804: _Script_name[999:1006],
	1936680815: _Script_name[1006:1016],
	1936683617: _Script_name[1016:1027],
	1936685423: _Script_name[1027:1034],
	1937075812: _Script_name[1034:1043],
	1937337455: _Script_name[1043:1054],
	1937338979: _Script_name[1054:1060],
	1952540514: _Script_name[1060:1068],
	1952541554: _Script_name[1068:1073],
	1952541797: _Script_name[1073:1078],
	1952541813: _Script_name[1078:1087],
	1952542060: _Script_name[1087:1092],
	1952542311: _Script_name[1092:1098],
	1952544372: _Script_name[1098:1105],
	1952803957: _Script_name[1105:1111],
	1952869991: _Script_name[1111:1119],
	1952935015: _Script_name[1119:1126],
	1952997729: _Script_name[1126:1132],
	1952997737: _Script_name[1132:1136],
	1953063540: _Script_name[1136:1143],
	1953067624: _Script_name[1143:1150],
	1969709426: _Script_name[1150:1158],
	1986095465: _Script_name[1158:1161],
	2002874977: _Script_name[1161:1171],
	2003003503: _Script_name[1171:1177],
	2020631919: _Script_name[1177:1187],
	2020832632: _Script_name[1187:1196],
	2036693609: _Script_name[1196:1202],
	2036951401: _Script_name[1202:1204],
	2053205602: _Script_name[1204:1219],
	2053729896: _Script_name[1219:1234],
	2054781305: _Script_name[1234:1246],
	2054847098: _Script_name[1246:1259],
}

func (i Script) String() string {
	if str, ok := _Script_map[i]; ok {
		return str
	}
	return "Script(" + strconv.FormatInt(int64(i), 10) + ")"
}
